const deck = {
    Easy: [
        { category: "Animals", items: ["cat", "dog", "fish", "bird", "rabbit", "cow", "duck", "sheep", "pig", "horse"] },
        { category: "Fruits", items: ["apple", "banana", "grapes", "pear", "orange", "watermelon", "lemon", "cherry", "strawberry", "peach"] },
        { category: "Vehicles", items: ["car", "bus", "bicycle", "boat", "train", "truck", "motorcycle", "plane", "helicopter", "submarine"] },
        { category: "Clothes", items: ["shirt", "trousers", "dress", "skirt", "hat", "shoes", "socks", "scarf", "gloves", "coat"] },
        { category: "Toys", items: ["ball", "doll", "teddy bear", "kite", "yo-yo", "robot", "puzzle", "blocks", "frisbee", "toy car"] },
        { category: "Food", items: ["pizza", "burger", "hotdog", "sandwich", "cake", "cookie", "ice cream", "fries", "egg", "bread"] },
        { category: "Nature", items: ["tree", "flower", "leaf", "mountain", "river", "cloud", "sun", "moon", "star", "rain"] },
        { category: "Household", items: ["chair", "table", "bed", "lamp", "clock", "door", "window", "cup", "plate", "spoon"] },
        { category: "Sports", items: ["football", "basketball", "tennis", "baseball", "golf", "skateboard", "skiing", "swimming", "bowling", "boxing"] },
        { category: "Jobs", items: ["chef", "firefighter", "police officer", "doctor", "nurse", "teacher", "artist", "farmer", "pilot", "builder"] },
        { category: "Musical Instruments", items: ["drum", "guitar", "piano", "trumpet", "violin", "flute", "harmonica", "tambourine", "triangle", "maracas"] },
        { category: "Sea Creatures", items: ["crab", "starfish", "jellyfish", "shrimp", "clam", "seal", "seahorse", "lobster", "turtle", "dolphin"] },
        { category: "Buildings", items: ["house", "tent", "castle", "igloo", "lighthouse", "windmill", "church", "store", "school", "fire station"] },
        { category: "Actions", items: ["running", "jumping", "sitting", "sleeping", "eating", "reading", "waving", "swimming", "dancing", "singing"] },
        { category: "Weather", items: ["rain", "snow", "wind", "sun", "cloud", "storm", "fog", "hail", "lightning", "rainbow"] },
        { category: "Insects", items: ["ant", "bee", "butterfly", "beetle", "ladybug", "mosquito", "dragonfly", "spider", "worm", "caterpillar"] },
        { category: "Emotions", items: ["happy", "sad", "angry", "excited", "bored", "scared", "sleepy", "surprised", "confused", "laughing"] },
        { category: "School", items: ["book", "pencil", "eraser", "ruler", "chalkboard", "desk", "backpack", "notebook", "glue", "scissors"] },
        { category: "Body Parts", items: ["hand", "foot", "eye", "ear", "mouth", "nose", "leg", "arm", "hair", "teeth"] },
        { category: "Candy", items: ["lollipop", "chocolate", "candy cane", "gum", "gummy bear", "jellybean", "marshmallow", "toffee", "caramel", "mint"] },
        { category: "Pets", items: ["dog", "cat", "rabbit", "hamster", "goldfish", "turtle", "parrot", "mouse", "frog", "snake"] },
        { category: "Fantasy", items: ["unicorn", "dragon", "fairy", "elf", "witch", "wizard", "goblin", "troll", "giant", "mermaid"] },
        { category: "Transport Parts", items: ["wheel", "engine", "steering wheel", "seatbelt", "mirror", "door", "trunk", "window", "pedal", "horn"] },
        { category: "Tools", items: ["hammer", "screwdriver", "saw", "wrench", "drill", "pliers", "tape measure", "nail", "axe", "toolbox"] }
    ],
    Medium: [
        { category: "Animals", items: ["elephant", "giraffe", "kangaroo", "penguin", "crocodile", "octopus", "owl", "bat", "crab", "snail"] },
        { category: "Fruits", items: ["pineapple", "watermelon", "kiwi", "mango", "avocado", "grapefruit", "coconut", "apricot", "plum", "lime"] },
        { category: "Vehicles", items: ["rocket", "canoe", "tractor", "scooter", "ambulance", "fire truck", "police car", "subway", "van", "zeppelin"] },
        { category: "Clothes", items: ["overalls", "tuxedo", "raincoat", "mittens", "boots", "tie", "belt", "vest", "blazer", "swimsuit"] },
        { category: "Toys", items: ["marbles", "slingshot", "spinning top", "action figure", "model plane", "puppet", "hula hoop", "jump rope", "drone", "water gun"] },
        { category: "Food", items: ["sushi", "taco", "croissant", "dumpling", "waffle", "burrito", "noodles", "omelette", "bagel", "meatball"] },
        { category: "Nature", items: ["cactus", "palm tree", "volcano", "waterfall", "island", "lightning", "tornado", "desert", "cave", "pond"] },
        { category: "Household", items: ["sofa", "bookshelf", "mirror", "toaster", "blender", "vacuum", "curtain", "fan", "remote", "teapot"] },
        { category: "Sports", items: ["hockey stick", "lacrosse stick", "vault pole", "diving board", "kayak", "bobsled", "shot put", "archery", "surfboard", "fencing sword"] },
        { category: "Jobs", items: ["scientist", "astronaut", "magician", "photographer", "mechanic", "plumber", "gardener", "musician", "dancer", "reporter"] },
        { category: "Musical Instruments", items: ["saxophone", "cello", "accordion", "banjo", "harp", "tuba", "clarinet", "oboe", "xylophone", "bagpipes"] },
        { category: "Sea Creatures", items: ["stingray", "orca", "eel", "sea urchin", "manatee", "walrus", "sea lion", "manta ray", "moray eel", "sea cucumber"] },
        { category: "Buildings", items: ["castle", "lighthouse", "windmill", "igloo", "bridge", "church", "skyscraper", "mosque", "pagoda", "arena"] },
        { category: "Actions", items: ["surfing", "skydiving", "juggling", "ice skating", "fencing", "scuba diving", "horse riding", "archery", "rowing", "parachuting"] },
        { category: "Weather", items: ["tornado", "hurricane", "blizzard", "hailstorm", "sandstorm", "thunderstorm", "snowstorm", "windy day", "cloudy sky", "sunny day"] },
        { category: "Fantasy Creatures", items: ["centaur", "phoenix", "griffin", "troll", "golem", "minotaur", "gargoyle", "hydra", "cyclops", "banshee"] },
        { category: "Camping", items: ["tent", "campfire", "backpack", "lantern", "sleeping bag", "compass", "map", "marshmallow stick", "hiking boots", "canteen"] },
        { category: "Outer Space", items: ["astronaut", "spaceship", "planet", "satellite", "alien", "moon rover", "asteroid", "UFO", "space station", "black hole"] },
        { category: "Fantasy Actions", items: ["flying", "casting spell", "sword fighting", "riding dragon", "potion making", "teleporting", "invisibility", "shape-shifting", "summoning", "fireball"] },
        { category: "Board Games", items: ["chess", "checkers", "monopoly", "dice", "cards", "scrabble", "jenga", "clue", "battleship", "dominoes"] },
        { category: "Technology", items: ["laptop", "smartphone", "VR headset", "camera", "keyboard", "joystick", "drone", "USB stick", "robot", "headphones"] },
        { category: "Occupations 2", items: ["zookeeper", "pilot", "DJ", "librarian", "clown", "barber", "tattoo artist", "delivery driver", "tailor", "security guard"] },
        { category: "Fairy Tale Items", items: ["magic wand", "glass slipper", "crown", "throne", "poison apple", "treasure chest", "magic mirror", "spell book", "cloak", "enchanted sword"] },
        { category: "Jungle", items: ["monkey", "parrot", "vine", "jungle hut", "banana tree", "snake", "toucan", "panther", "bamboo", "tree frog"] },
        { category: "Pirates", items: ["pirate", "treasure", "ship", "map", "parrot", "sword", "cannon", "eyepatch", "hook", "flag"] }

    ],
    Hard: [
        { category: "Animals", items: ["platypus", "narwhal", "armadillo", "sloth", "rhino", "chameleon", "iguana", "llama", "wombat", "porcupine"] },
        { category: "Fruits", items: ["dragonfruit", "starfruit", "papaya", "passion fruit", "cantaloupe", "lychee", "persimmon", "guava", "pomelo", "honeydew"] },
        { category: "Vehicles", items: ["rickshaw", "segway", "hoverboard", "monorail", "dog sled", "hot air balloon", "hang glider", "unicycle", "gondola", "tandem bike"] },
        { category: "Clothes", items: ["kimono", "sari", "poncho", "balaclava", "lederhosen", "cape", "toga", "beret", "corset", "clogs"] },
        { category: "Toys", items: ["Rubik's cube", "model train", "slot car", "yo-yo trick", "remote control car", "pogo stick", "stilts", "magic set", "chemistry set", "model rocket"] },
        { category: "Food", items: ["paella", "souffle", "ratatouille", "baklava", "spring roll", "cannoli", "tamale", "bibimbap", "pierogi", "samosa"] },
        { category: "Nature", items: ["geyser", "stalactite", "stalagmite", "avalanche", "tsunami", "eclipse", "aurora", "reef", "mesa", "glacier"] },
        { category: "Household", items: ["grandfather clock", "chandelier", "radiator", "projector", "juicer", "ironing board", "fireplace", "alarm clock", "dishwasher", "mop"] },
        { category: "Sports", items: ["curling stone", "polo mallet", "javelin", "luge", "cricket bat", "snooker cue", "paraglider", "windsurf board", "paddleboard", "boomerang"] },
        { category: "Jobs", items: ["scuba diver", "mountain guide", "puppeteer", "beekeeper", "ventriloquist", "sumo wrestler", "stunt double", "cartographer", "lighthouse keeper", "snake charmer"] },
        { category: "Musical Instruments", items: ["didgeridoo", "mandolin", "ukulele", "ocarina", "sitar", "pan flute", "recorder", "banjo", "zither", "bassoon"] },
        { category: "Sea Creatures", items: ["giant squid", "blue whale", "anglerfish", "nautilus", "sea dragon", "blobfish", "gulper eel", "vampire squid", "coelacanth", "frilled shark"] },
        { category: "Buildings", items: ["treehouse", "observatory", "palace", "fortress", "amphitheater", "pyramid", "cathedral", "colosseum", "museum", "prison"] },
        { category: "Actions", items: ["tightrope walking", "fire breathing", "unicycling", "pole vaulting", "bungee jumping", "sword swallowing", "breakdancing", "parkour", "plate spinning", "log rolling"] },
        { category: "Weather", items: ["thunderstorm", "ice storm", "dust storm", "dust devil", "cold front", "whirlwind", "downpour", "waterspout", "lightning", "rainbow"] },
        { category: "Mythological Creatures", items: ["kraken", "basilisk", "chimera", "cerberus", "leviathan", "dryad", "pegasus", "selkie", "wendigo", "djinn"] },
        { category: "Scientific Items", items: ["microscope", "telescope", "petri dish", "test tube", "atom", "beaker", "Bunsen burner", "circuit board", "vortex", "lab coat"] },
        { category: "Architectural Structures", items: ["aqueduct", "viaduct", "gazebo", "obelisk", "rotunda", "dome", "minaret", "colonnade", "drawbridge", "triumphal arch"] },
        { category: "Esoteric Jobs", items: ["forensic artist", "haberdasher", "glassblower", "luthier", "taxidermist", "blacksmith", "sommelier", "meteorologist", "geologist", "historian"] },
        { category: "World Instruments", items: ["djembe", "marimba", "steel drum", "bongo drums", "kalimba", "rain stick", "cowbell", "wind chimes", "gong", "castanets"] },
        { category: "Rare Vehicles", items: ["amphibious car", "icebreaker", "gyroplane", "land yacht", "rail bike", "hydrofoil", "snowcat", "autogyro", "aerial tramway", "hovercraft"] },
        { category: "Advanced Emotions", items: ["jealous", "worried", "amazed", "envious", "embarrassed", "anxious", "relieved", "disgusted", "curious", "proud"] },
        { category: "Legendary Creatures", items: ["bigfoot", "loch ness monster", "yeti", "vampire", "werewolf", "zombie", "ghost", "alien", "monster", "giant"] },
        { category: "Complex Actions", items: ["meditating", "conducting orchestra", "painting", "climbing", "knitting", "whispering", "lifting weights", "building", "balancing", "stretching"] },
        { category: "Steampunk", items: ["goggles", "gear", "pocket watch", "steam engine", "mechanical arm", "zeppelin", "brass pipe", "control panel", "ray gun", "airship"] }
    ]
};