const deck = {
    Easy: [
        { category: "Animals", items: ["cat", "dog", "fish", "bird", "rabbit", "cow", "duck", "sheep", "pig", "horse"] },
        { category: "Fruits", items: ["apple", "banana", "grapes", "pear", "pineapple", "watermelon", "kiwi", "cherry", "strawberry", "blueberry"] },
        { category: "Vehicles", items: ["car", "bus", "bicycle", "boat", "train", "truck", "motorcycle", "plane", "helicopter", "submarine"] },
        { category: "Clothes", items: ["shirt", "trousers", "dress", "skirt", "hat", "shoes", "socks", "scarf", "gloves", "coat"] },
        { category: "Toys", items: ["ball", "doll", "teddy bear", "kite", "yo-yo", "robot", "puzzle", "rubix cube", "frisbee", "jack in the box"] },
        { category: "Food", items: ["pizza", "burger", "hotdog", "sandwich", "cake", "cookie", "ice cream", "fries", "egg", "bread"] },
        { category: "Nature", items: ["tree", "flower", "leaf", "mountain", "river", "cloud", "sun", "moon", "star", "rain"] },
        { category: "Household", items: ["chair", "table", "bed", "lamp", "clock", "door", "window", "cup", "plate", "spoon"] },
        { category: "Sports", items: ["football", "basketball", "tennis", "baseball", "golf", "skateboard", "skiing", "swimming", "bowling", "boxing"] },
        { category: "Jobs", items: ["chef", "firefighter", "police officer", "doctor", "nurse", "teacher", "artist", "farmer", "pilot", "builder"] },
        { category: "Musical Instruments", items: ["drum", "guitar", "piano", "trumpet", "violin", "flute", "harmonica", "tambourine", "triangle", "maracas"] },
        { category: "Sea Creatures", items: ["crab", "starfish", "jellyfish", "shrimp", "clam", "seal", "seahorse", "lobster", "turtle", "dolphin"] },
        { category: "Buildings", items: ["house", "tent", "castle", "igloo", "lighthouse", "windmill", "church", "store", "school", "fire station"] },
        { category: "Actions", items: ["running", "jumping", "sitting", "sleeping", "eating", "reading", "waving", "swimming", "dancing", "singing"] },
        { category: "Weather", items: ["rain", "snow", "wind", "sun", "cloud", "storm", "fog", "hail", "lightning", "rainbow"] },
        { category: "Insects", items: ["ant", "bee", "butterfly", "beetle", "ladybug", "mosquito", "dragonfly", "spider", "worm", "caterpillar"] },
        { category: "Emotions", items: ["happy", "sad", "angry", "excited", "bored", "scared", "sleepy", "surprised", "confused", "laughing"] },
        { category: "School", items: ["book", "pencil", "eraser", "ruler", "chalkboard", "desk", "backpack", "notebook", "glue", "scissors"] },
        { category: "Body Parts", items: ["hand", "foot", "eye", "ear", "mouth", "nose", "leg", "arm", "hair", "teeth"] },
        { category: "Candy", items: ["lollipop", "chocolate", "candy cane", "gum", "gummy bear", "jellybean", "marshmallow", "toffee", "caramel", "mint"] },
        { category: "Pets", items: ["dog", "cat", "rabbit", "hamster", "goldfish", "turtle", "parrot", "mouse", "frog", "snake"] },
        { category: "Fantasy", items: ["unicorn", "dragon", "fairy", "elf", "witch", "wizard", "goblin", "troll", "giant", "mermaid"] },
        { category: "Transport Parts", items: ["wheel", "engine", "steering wheel", "seatbelt", "mirror", "door", "trunk", "window", "pedal", "horn"] },
        { category: "Tools", items: ["hammer", "screwdriver", "saw", "wrench", "drill", "pliers", "tape measure", "nail", "axe", "toolbox"] }
    ],
    Medium: [
        { category: "Animals", items: ["elephant", "giraffe", "kangaroo", "penguin", "crocodile", "octopus", "owl", "bat", "crab", "snail"] },
        { category: "Fruits", items: ["pineapple", "watermelon", "kiwi", "mango", "pomegranate", "grapefruit", "coconut", "apricot", "fig", "lime"] },
        { category: "Vehicles", items: ["rocket", "canoe", "tractor", "scooter", "ambulance", "fire truck", "police car", "subway", "van", "zeppelin"] },
        { category: "Clothes", items: ["overalls", "tuxedo", "raincoat", "mittens", "boots", "tie", "belt", "vest", "blazer", "swimsuit"] },
        { category: "Toys", items: ["marbles", "slingshot", "spinning top", "action figure", "model plane", "puppet", "hula hoop", "jump rope", "drone", "water gun"] },
        { category: "Food", items: ["sushi", "taco", "croissant", "dumpling", "waffle", "burrito", "noodles", "omelette", "bagel", "meatball"] },
        { category: "Nature", items: ["cactus", "palm tree", "volcano", "waterfall", "island", "lightning", "tornado", "desert", "cave", "pond"] },
        { category: "Household", items: ["sofa", "bookshelf", "mirror", "toaster", "blender", "vacuum", "curtain", "fan", "remote", "teapot"] },
        { category: "Sports", items: ["hockey stick", "lacrosse stick", "vault pole", "diving board", "kayak", "bobsled", "shot put", "archery", "surfboard", "fencing sword"] },
        { category: "Jobs", items: ["scientist", "astronaut", "magician", "photographer", "mechanic", "plumber", "gardener", "musician", "dancer", "reporter"] },
        { category: "Musical Instruments", items: ["saxophone", "cello", "accordion", "banjo", "harp", "tuba", "clarinet", "oboe", "xylophone", "bagpipes"] },
        { category: "Sea Creatures", items: ["stingray", "orca", "eel", "sea urchin", "manatee", "walrus", "sea lion", "manta ray", "moray eel", "sea cucumber"] },
        { category: "Buildings", items: ["castle", "lighthouse", "windmill", "igloo", "bridge", "church", "skyscraper", "mosque", "pagoda", "arena"] },
        { category: "Actions", items: ["surfing", "skydiving", "juggling", "ice skating", "fencing", "scuba diving", "horse riding", "archery", "rowing", "parachuting"] },
        { category: "Weather", items: ["tornado", "hurricane", "blizzard", "hailstorm", "sandstorm", "tsunami", "volcano eruption", "drought", "monsoon", "cyclone"] },
        { category: "Insects", items: ["mantis", "stag beetle", "firefly", "cicada", "hornet", "weevil", "stick insect", "mayfly", "lacewing", "silverfish"] },
        { category: "Emotions", items: ["jealous", "embarrassed", "proud", "ashamed", "relieved", "nervous", "hopeful", "disgusted", "guilty", "shy"] },
        { category: "School", items: ["calculator", "protractor", "compass", "whiteboard", "projector", "binder", "clipboard", "highlighter", "stapler", "paperclip"] },
        { category: "Body Parts", items: ["ankle", "elbow", "chin", "wrist", "thumb", "eyebrow", "shoulder", "heel", "tongue", "knuckle"] },
        { category: "Candy", items: ["jawbreaker", "taffy", "rock candy", "fudge", "licorice", "peanut brittle", "toffee apple", "candy corn", "fruit leather", "sherbet"] },
        { category: "Pets", items: ["ferret", "chinchilla", "parakeet", "iguana", "tarantula", "hedgehog", "salamander", "gecko", "rat", "hermit crab"] },
        { category: "Fantasy", items: ["centaur", "phoenix", "griffin", "troll", "golem", "minotaur", "gargoyle", "hydra", "cyclops", "banshee"] },
        { category: "Transport Parts", items: ["axle", "gearbox", "dashboard", "windscreen", "bumper", "headlight", "exhaust", "hubcap", "indicator", "radiator"] },
        { category: "Tools", items: ["chisel", "mallet", "plane", "rasp", "vise", "awl", "level", "crowbar", "soldering iron", "trowel"] }
    ],
    Hard: [
        { category: "Animals", items: ["platypus", "narwhal", "armadillo", "sloth", "pangolin", "chameleon", "axolotl", "tapir", "wombat", "aardvark"] },
        { category: "Fruits", items: ["dragonfruit", "starfruit", "durian", "jackfruit", "rambutan", "lychee", "persimmon", "tamarillo", "longan", "salak"] },
        { category: "Vehicles", items: ["rickshaw", "segway", "hoverboard", "monorail", "dog sled", "hot air balloon", "hang glider", "unicycle", "gondola", "tandem bike"] },
        { category: "Clothes", items: ["kimono", "sari", "poncho", "balaclava", "lederhosen", "cape", "toga", "beret", "corset", "clogs"] },
        { category: "Toys", items: ["Rubik's cube", "model train", "slot car", "yo-yo trick", "remote control car", "pogo stick", "stilts", "magic set", "chemistry set", "model rocket"] },
        { category: "Food", items: ["paella", "souffle", "ratatouille", "baklava", "spring roll", "cannoli", "tamale", "bibimbap", "pierogi", "samosa"] },
        { category: "Nature", items: ["geyser", "stalactite", "stalagmite", "avalanche", "tsunami", "eclipse", "aurora", "reef", "mesa", "glacier"] },
        { category: "Household", items: ["grandfather clock", "chandelier", "radiator", "projector", "juicer", "ironing board", "fireplace", "alarm clock", "dishwasher", "mop"] },
        { category: "Sports", items: ["curling stone", "polo mallet", "javelin", "luge", "cricket bat", "snooker cue", "paraglider", "windsurf board", "paddleboard", "boomerang"] },
        { category: "Jobs", items: ["scuba diver", "mountain guide", "puppeteer", "beekeeper", "ventriloquist", "sumo wrestler", "stunt double", "cartographer", "lighthouse keeper", "snake charmer"] },
        { category: "Musical Instruments", items: ["didgeridoo", "hurdy-gurdy", "theremin", "ocarina", "sitar", "pan flute", "glass harmonica", "shamisen", "zither", "contrabassoon"] },
        { category: "Sea Creatures", items: ["giant squid", "blue whale", "anglerfish", "nautilus", "sea dragon", "blobfish", "gulper eel", "vampire squid", "coelacanth", "frilled shark"] },
        { category: "Buildings", items: ["treehouse", "observatory", "palace", "fortress", "amphitheater", "pyramid", "cathedral", "colosseum", "museum", "prison"] },
        { category: "Actions", items: ["tightrope walking", "fire breathing", "unicycling", "pole vaulting", "bungee jumping", "sword swallowing", "breakdancing", "parkour", "plate spinning", "log rolling"] },
        { category: "Weather", items: ["supercell", "derecho", "ice storm", "dust devil", "polar vortex", "fire whirl", "microburst", "waterspout", "ball lightning", "sun dog"] },
        { category: "Insects", items: ["atlas moth", "goliath beetle", "stick insect", "mantis shrimp", "giant weta", "tarantula hawk", "assassin bug", "bombardier beetle", "antlion", "dobsonfly"] },
        { category: "Emotions", items: ["nostalgia", "melancholy", "awe", "envy", "embarrassment", "anxiety", "relief", "disgust", "curiosity", "pride"] },
        { category: "School", items: ["microscope", "telescope", "petri dish", "test tube", "atom", "beaker", "Bunsen burner", "circuit board", "vortex", "lab coat"] },
        { category: "Body Parts", items: ["uvula", "sternum", "scapula", "patella", "phalanx", "metatarsal", "coccyx", "clavicle", "mandible", "fibula"] },
        { category: "Candy", items: ["halvah", "turkish delight", "pocky", "mochi", "dulce de leche", "marzipan", "nougat", "divinity", "pastille", "aniseed ball"] },
        { category: "Pets", items: ["axolotl", "sugar glider", "fancy rat", "tarantula", "hermit crab", "gecko", "skunk", "hedgehog", "salamander", "ferret"] },
        { category: "Fantasy", items: ["kraken", "basilisk", "chimera", "cerberus", "leviathan", "dryad", "pegasus", "selkie", "wendigo", "djinn"] },
        { category: "Transport Parts", items: ["differential", "universal joint", "catalytic converter", "flywheel", "strut", "torsion bar", "solenoid", "idler arm", "kingpin", "rocker panel"] },
        { category: "Tools", items: ["adze", "reamer", "spokeshave", "caliper", "gimlet", "drawknife", "bradawl", "nibbler", "punch", "scriber"] }
    ]
};
