const deck = {
    Easy: [
        { category: "Animals", items: ["cat", "dog", "fish", "bird", "rabbit", "cow", "duck", "sheep", "pig", "horse"] },
        { category: "Fruits", items: ["apple", "banana", "grapes", "pear", "orange", "watermelon", "lemon", "cherry", "strawberry", "pineapple"] },
        { category: "Vehicles", items: ["car", "bus", "bicycle", "boat", "train", "truck", "motorcycle", "plane", "helicopter", "scooter"] },
        { category: "Clothes", items: ["shirt", "trousers", "dress", "skirt", "hat", "shoes", "socks", "scarf", "gloves", "coat"] },
        { category: "Toys", items: ["ball", "doll", "teddy bear", "kite", "yo-yo", "robot", "balloon", "blocks", "crayons", "toy car"] },
        { category: "Food", items: ["pizza", "burger", "hotdog", "chocolate", "cake", "cookie", "ice cream", "fries", "fried egg", "bread"] },
        { category: "Nature", items: ["tree", "flower", "leaf", "mountain", "river", "cloud", "sun", "moon", "star", "hill"] },
        { category: "Household", items: ["chair", "table", "bed", "lamp", "clock", "door", "window", "cup", "plate", "spoon"] },
        { category: "Sports", items: ["football", "basketball", "tennis racket", "baseball bat", "golf club", "skateboard", "skiing", "swimming", "bowling", "boxing"] },
        { category: "Jobs", items: ["chef", "firefighter", "police officer", "doctor", "nurse", "teacher", "artist", "farmer", "clown", "builder"] },
        { category: "Musical Instruments", items: ["drum", "guitar", "piano", "trumpet", "violin", "recorder", "ukulele", "tambourine", "bell", "maracas"] },
        { category: "Sea Creatures", items: ["crab", "starfish", "jellyfish", "whale", "shark", "seal", "seahorse", "lobster", "turtle", "dolphin"] },
        { category: "Actions", items: ["running", "jumping", "sitting", "sleeping", "eating", "reading", "waving", "swimming", "dancing", "singing"] },
        { category: "Weather", items: ["rainy", "snowy", "icy", "sunny", "cloudy", "stormy", "tornado", "hail", "windy", "rainbow"] },
        { category: "Emotions", items: ["happy", "sad", "angry", "excited", "bored", "scared", "sleepy", "surprised", "confused", "laughing"] },
        { category: "School", items: ["book", "pencil", "eraser", "ruler", "chalkboard", "desk", "backpack", "notebook", "glue", "scissors"] },
        { category: "Body Parts", items: ["hand", "foot", "eye", "ear", "mouth", "nose", "leg", "arm", "hair", "teeth"] },
        { category: "Candy", items: ["lollipop", "chocolate", "candy cane", "marshmallow", "gummy bear", "cupcake", "donut", "ice lolly", "cotton candy", "gingerbread man"] },
        { category: "Fantasy", items: ["unicorn", "dragon", "fairy", "elf", "witch", "wizard", "ghost", "cauldron", "broomstick", "mermaid"] },
        { category: "Transport Parts", items: ["wheel", "headlight", "steering wheel", "bumper", "antenna", "door", "trunk", "window", "seat", "license plate"] },
        { category: "Tools", items: ["hammer", "screwdriver", "saw", "spanner", "paintbrush", "pliers", "screw", "nail", "axe", "toolbox"] },
        { category: "Hats", items: ["top hat", "baseball cap", "beanie", "cowboy hat", "sombrero", "helmet", "bowler hat", "sun hat", "party hat", "chef's hat"] },
        { category: "Cooking Utensils", items: ["spatula", "whisk", "rolling pin", "ladle", "tongs", "frying pan", "oven mitt", "knife", "cutting board", "can opener"] },
        { category: "Toiletries", items: ["toothbrush", "toothpaste", "soap", "shampoo", "razor", "comb", "hairbrush", "towel", "deodorant", "cotton bud"] },
        { category: "Vegetables", items: ["carrot", "broccoli", "potato", "onion", "tomato", "mushroom", "pepper", "cucumber", "lettuce", "celery"] },
        { category: "Drinks", items: ["coffee", "tea", "milk carton", "juice box", "water bottle", "soda can", "wine glass", "beer mug", "smoothie", "cocktail"] },
        { category: "Office Supplies", items: ["stapler", "paperclip", "calculator", "sticky note", "envelope", "hole punch", "printer", "whiteboard", "tape dispenser", "file folder"] },
        { category: "Symbols", items: ["heart", "peace", "yin yang", "arrow", "dollar", "infinity", "recycling", "lightning", "music", "hashtag"] },
        { category: "Christmas", items: ["Christmas tree", "Santa", "snowman", "reindeer", "present", "stocking", "ornament", "wreath", "sleigh", "chimney"] },
    ],
    Medium: [
        { category: "Animals", items: ["elephant", "giraffe", "kangaroo", "penguin", "crocodile", "octopus", "owl", "snail", "rhino", "llama"] },
        { category: "Fruits", items: ["peach", "kiwi", "mango", "avocado", "grapefruit", "coconut", "apricot", "pumpkin", "corn", "lime"] },
        { category: "Vehicles", items: ["rocket", "canoe", "tractor", "submarine", "ambulance", "jet ski", "police car", "subway", "forklift", "zeppelin"] },
        { category: "Clothes", items: ["overalls", "tuxedo", "raincoat", "mittens", "boots", "pajamas", "apron", "vest", "hoodie", "swimsuit"] },
        { category: "Toys", items: ["marbles", "slingshot", "spinning top", "puzzle", "model plane", "frisbee", "hula hoop", "jump rope", "drone", "water gun"] },
        { category: "Food", items: ["sushi", "taco", "croissant", "dumpling", "waffle", "burrito", "noodles", "omelette", "bagel", "meatball"] },
        { category: "Nature", items: ["cactus", "palm tree", "volcano", "waterfall", "island", "beach", "valley", "swamp", "cave", "pond"] },
        { category: "Household", items: ["sofa", "bookshelf", "mirror", "toaster", "blender", "vacuum", "curtain", "fan", "remote", "teapot"] },
        { category: "Sports", items: ["hockey stick", "snowboard", "dumbbell", "diving board", "kayak", "bobsled", "badminton racket", "ping pong paddle", "surfboard", "rugby ball"] },
        { category: "Jobs", items: ["scientist", "lifeguard", "magician", "photographer", "mechanic", "plumber", "gardener", "musician", "dancer", "reporter"] },
        { category: "Musical Instruments", items: ["saxophone", "cello", "harmonica", "banjo", "harp", "tuba", "clarinet", "flute", "xylophone", "triangle"] },
        { category: "Sea Creatures", items: ["stingray", "orca", "eel", "sea urchin", "manatee", "walrus", "sea lion", "shark", "pufferfish", "sea cucumber"] },
        { category: "Buildings", items: ["castle", "lighthouse", "windmill", "igloo", "bridge", "church", "skyscraper", "train station", "pagoda", "pyramid"] },
        { category: "Actions", items: ["surfing", "skydiving", "juggling", "ice skating", "fencing", "scuba diving", "horse riding", "archery", "rowing", "parachuting"] },
        { category: "Weather", items: ["blizzard", "hailstorm", "sandstorm", "thunderstorm", "wind", "fog", "drizzle", "mist", "monsoon", "sleet"] },
        { category: "Fantasy Creatures", items: ["centaur", "phoenix", "griffin", "troll", "golem", "minotaur", "gargoyle", "pegasus", "goblin", "giant"] },
        { category: "Camping", items: ["hammock", "campfire", "fishing rod", "lantern", "sleeping bag", "compass", "map", "marshmallow stick", "hiking boots", "canteen"] },
        { category: "Outer Space", items: ["astronaut", "spaceship", "planet", "satellite", "alien", "moon rover", "black hole", "UFO", "space station", "galaxy"] },
        { category: "Fantasy Actions", items: ["flying", "casting spell", "sword fighting", "riding dragon", "potion making", "enchanting", "levitating", "dueling", "slaying dragon", "fireball"] },
        { category: "Board Games", items: ["chess", "checkers", "monopoly", "dice", "cards", "backgammon", "jenga", "twister", "poker chips", "dominoes"] },
        { category: "Technology", items: ["laptop", "smartphone", "VR headset", "camera", "keyboard", "joystick", "tablet", "USB stick", "smartwatch", "headphones"] },
        { category: "Occupations 2", items: ["zookeeper", "pilot", "DJ", "vet", "mailman", "barber", "tattoo artist", "delivery driver", "tailor", "security guard"] },
        { category: "Fairy Tale Items", items: ["magic wand", "glass slipper", "crown", "throne", "poison apple", "treasure chest", "magic mirror", "spell book", "cloak", "enchanted sword"] },
        { category: "Jungle", items: ["gorilla", "jaguar", "vine", "jungle hut", "banana tree", "anaconda", "toucan", "panther", "bamboo", "tree frog"] },
        { category: "Pirates", items: ["pirate", "treasure", "doubloon", "anchor", "spyglass", "cutlass", "cannon", "eyepatch", "hook", "peg leg"] },
        { category: "Gardening Equipment", items: ["spade", "rake", "watering can", "wheelbarrow", "hose", "lawn mower", "shears", "trowel", "sprinkler", "hedge trimmer"] },
        { category: "Jewellery", items: ["ring", "necklace", "earrings", "bracelet", "watch", "locket", "pendant", "brooch", "anklet", "cufflinks"] },
        { category: "Hair Styles", items: ["ponytail", "bun", "mohawk", "braid", "afro", "bald", "mullet", "bob", "dreadlocks", "pigtails"] },
        { category: "Dinosaurs", items: ["T-rex", "triceratops", "stegosaurus", "pterodactyl", "velociraptor", "brachiosaurus", "ankylosaurus", "diplodocus", "parasaurolophus", "mosasaurus"] },
        { category: "Birds", items: ["eagle", "swan", "flamingo", "woodpecker", "peacock", "ostrich", "pelican", "hummingbird", "robin", "hawk"] },
        { category: "Insects 2", items: ["grasshopper", "praying mantis", "scorpion", "wasp", "hornet", "cricket", "cockroach", "termite", "firefly", "millipede"] },
        { category: "Power Tools", items: ["drill", "jackhammer", "chainsaw", "sander", "circular saw", "nail gun", "table saw", "leaf blower", "angle grinder", "pressure washer"] },
        { category: "Pets", items: ["dog", "cat", "rabbit", "hamster", "fish", "turtle", "parrot", "mouse", "frog", "snake"] },
        { category: "Insects", items: ["ant", "bee", "butterfly", "beetle", "ladybug", "centipede", "dragonfly", "spider", "worm", "mosquito"] },
    ],
    Hard: [
        { category: "Animals", items: ["platypus", "narwhal", "armadillo", "sloth", "pangolin", "chameleon", "iguana", "axolotl", "wombat", "porcupine"] },
        { category: "Fruits", items: ["dragonfruit", "starfruit", "papaya", "passion fruit", "jackfruit", "lychee", "durian", "rambutan", "pomegranate", "fig"] },
        { category: "Snacks", items: ["pretzel", "popcorn", "chips", "peanuts", "cracker", "nachos", "trail mix", "jerky", "granola bar", "rice cake"] },
        { category: "Vehicles", items: ["rickshaw", "segway", "hoverboard", "monorail", "dog sled", "hot air balloon", "hang glider", "unicycle", "gondola", "tandem bike"] },
        { category: "Clothes", items: ["kimono", "sari", "poncho", "balaclava", "lederhosen", "cape", "toga", "beret", "corset", "clogs"] },
        { category: "Toys", items: ["Rubik's cube", "model train", "slot car", "jack-in-the-box", "kaleidoscope", "pogo stick", "stilts", "etch-a-sketch", "slinky", "model rocket"] },
        { category: "Food", items: ["paella", "souffle", "ratatouille", "baklava", "spring roll", "cannoli", "tamale", "bibimbap", "pierogi", "samosa"] },
        { category: "Nature", items: ["geyser", "stalactite", "fjord", "avalanche", "tsunami", "eclipse", "aurora", "reef", "mesa", "glacier"] },
        { category: "Household", items: ["grandfather clock", "chandelier", "radiator", "projector", "juicer", "espresso machine", "fireplace", "sewing machine", "dishwasher", "humidifier"] },
        { category: "Sports", items: ["curling stone", "polo mallet", "javelin", "luge", "cricket bat", "snooker cue", "paraglider", "windsurf board", "pommel horse", "boomerang"] },
        { category: "Jobs", items: ["scuba diver", "mountain guide", "puppeteer", "beekeeper", "ventriloquist", "sumo wrestler", "stunt double", "cartographer", "lighthouse keeper", "snake charmer"] },
        { category: "Musical Instruments", items: ["didgeridoo", "mandolin", "theremin", "ocarina", "sitar", "pan flute", "lyre", "dulcimer", "zither", "bassoon"] },
        { category: "Sea Creatures", items: ["giant squid", "lionfish", "anglerfish", "nautilus", "sea dragon", "blobfish", "gulper eel", "vampire squid", "coelacanth", "frilled shark"] },
        { category: "Buildings", items: ["treehouse", "observatory", "ziggurat", "fortress", "amphitheater", "monastery", "planetarium", "mausoleum", "museum", "prison"] },
        { category: "Actions", items: ["tightrope walking", "fire breathing", "unicycling", "pole vaulting", "bungee jumping", "sword swallowing", "breakdancing", "parkour", "plate spinning", "log rolling"] },
        { category: "Weather", items: ["tornado", "ice storm", "dust storm", "typhoon", "supercell", "whirlwind", "polar vortex", "waterspout", "microburst", "virga"] },
        { category: "Mythological Creatures", items: ["kraken", "basilisk", "chimera", "cerberus", "leviathan", "dryad", "banshee", "selkie", "wendigo", "djinn"] },
        { category: "Scientific Items", items: ["microscope", "telescope", "petri dish", "test tube", "atom", "beaker", "Bunsen burner", "circuit board", "DNA helix", "prism"] },
        { category: "Architectural Structures", items: ["aqueduct", "gazebo", "obelisk", "spire", "pergola", "dome", "minaret", "colonnade", "drawbridge", "triumphal arch"] },
        { category: "Esoteric Jobs", items: ["forensic artist", "haberdasher", "glassblower", "luthier", "taxidermist", "blacksmith", "sommelier", "meteorologist", "geologist", "falconer"] },
        { category: "World Instruments", items: ["djembe", "marimba", "steel drum", "bongo drums", "kalimba", "rain stick", "tabla", "wind chimes", "hang drum", "castanets"] },
        { category: "Rare Vehicles", items: ["amphibious car", "icebreaker", "gyroplane", "land yacht", "rail bike", "hydrofoil", "snowcat", "jet pack", "aerial tramway", "hovercraft"] },
        { category: "Advanced Emotions", items: ["jealous", "smug", "suspicious", "mischievous", "embarrassed", "anxious", "relieved", "disgusted", "curious", "proud"] },
        { category: "Legendary Creatures", items: ["bigfoot", "loch ness monster", "chupacabra", "vampire", "werewolf", "zombie", "mothman", "poltergeist", "ogre", "jackalope"] },
        { category: "Complex Actions", items: ["meditating", "conducting orchestra", "yodeling", "climbing", "knitting", "contortion", "lifting weights", "ballroom dancing", "balancing", "mime acting"] },
        { category: "Steampunk", items: ["monocle", "pressure gauge", "pocket watch", "steam engine", "mechanical arm", "automaton", "brass pipe", "control panel", "ray gun", "smokestack"] },
        { category: "Extreme Sports", items: ["wingsuit flying", "base jumping", "ice climbing", "kitesurfing", "big wave surfing", "motocross", "BMX", "slacklining", "free diving", "white water rafting"] },
        { category: "Flags", items: ["Union Jack", "Stars and Stripes", "Japan", "Canada", "Brazil", "Jolly Roger", "checkered flag", "white flag", "pride flag", "Olympic rings"] },
        { category: "Country Outlines", items: ["Italy", "UK", "Japan", "Australia", "India", "USA", "France", "Madagascar", "Greenland", "Brazil"] },
        { category: "Famous Landmarks", items: ["Eiffel Tower", "Statue of Liberty", "Big Ben", "Sydney Opera House", "Leaning Tower of Pisa", "Taj Mahal", "Mount Rushmore", "Great Wall", "Stonehenge", "Christ the Redeemer"] },
        { category: "Yoga Poses", items: ["downward dog", "tree pose", "warrior pose", "child's pose", "lotus", "cobra", "plank", "eagle pose", "crow pose", "headstand"] },
        { category: "Constellations", items: ["Orion", "Big Dipper", "Cassiopeia", "Ursa Major", "Leo", "Scorpius", "Pisces", "Gemini", "Sagittarius", "Lyra"] }
    ]
};
